export interface GlossaryTerm {
  term: string;
  definition: string;
  category: string;
}

export const glossaryTerms: GlossaryTerm[] = [
  { term: "ACL (Access Control List)", definition: "a table that tells a computer operating system which access rights each user has to a particular system object, such as a file directory or individual file.", category: "Security" },
  { term: "ACID", definition: "a set of properties (atomicity, consistency, isolation, durability) that guarantee database transactions are processed reliably.", category: "PostgreSQL" },
  { term: "ACID compliance", definition: "a set of database properties—Atomicity, Consistency, Isolation, Durability—ensuring reliable and consistent transactions. Inherited from PostgreSQL.", category: "PostgreSQL" },
  { term: "Adaptive query optimization", definition: "dynamic query plan adjustment based on actual execution statistics and data distribution patterns, improving performance over time.", category: "PostgreSQL" },
  { term: "Aggregate (Continuous Aggregate)", definition: "a materialized, precomputed summary of query results over time-series data, providing faster access to analytics.", category: "TimescaleDB" },
  { term: "Alerting", definition: "the process of automatically notifying administrators when predefined conditions or thresholds are met in system monitoring.", category: "Observability" },
  { term: "Analytics database", definition: "a system optimized for large-scale analytical queries, supporting complex aggregations, time-based queries, and data exploration.", category: "Data & migration" },
  { term: "Anomaly detection", definition: "the identification of abnormal patterns or outliers within time-series datasets, common in observability, IoT, and finance.", category: "Time-series" },
  { term: "Append-only storage", definition: "a storage pattern where data is only added, never modified in place. Ideal for time-series workloads and audit trails.", category: "Storage" },
  { term: "Archival", definition: "the process of moving old or infrequently accessed data to long-term, cost-effective storage solutions.", category: "Storage" },
  { term: "Auto-partitioning", definition: "automatic division of a hypertable into chunks based on partitioning dimensions to optimize scalability and performance.", category: "TimescaleDB" },
  { term: "Availability zone", definition: "an isolated location within a cloud region that provides redundant power, networking, and connectivity.", category: "Cloud" },
  { term: "B-tree", definition: "a self-balancing tree data structure that maintains sorted data and allows searches, sequential access, insertions, and deletions in logarithmic time.", category: "PostgreSQL" },
  { term: "Background job", definition: "an automated task that runs in the background without user intervention, typically for maintenance operations like compression or data retention.", category: "Operations" },
  { term: "Background worker", definition: "a PostgreSQL process that runs background tasks independently of client sessions.", category: "PostgreSQL" },
  { term: "Batch processing", definition: "handling data in grouped batches rather than as individual real-time events, often used for historical data processing.", category: "Data & migration" },
  { term: "Backfill", definition: "the process of filling in historical data that was missing or needs to be recalculated, often used during migrations or after schema changes.", category: "Data & migration" },
  { term: "Backup", definition: "a copy of data stored separately from the original data to protect against data loss, corruption, or system failure.", category: "Operations" },
  { term: "Bloom filter", definition: "a probabilistic data structure that tests set membership with possible false positives but no false negatives. TimescaleDB uses blocked bloom filters to speed up point lookups by eliminating chunks that don’t contain queried values.", category: "TimescaleDB" },
  { term: "Buffer pool", definition: "memory area where frequently accessed data pages are cached to reduce disk I/O operations.", category: "PostgreSQL" },
  { term: "BRIN (Block Range Index)", definition: "a PostgreSQL index type that stores summaries about ranges of table blocks, useful for large tables with naturally ordered data.", category: "PostgreSQL" },
  { term: "Bytea", definition: "a PostgreSQL data type for storing binary data as a sequence of bytes.", category: "PostgreSQL" },
  { term: "Cache hit ratio", definition: "the percentage of data requests served from memory cache rather than disk, indicating query performance efficiency.", category: "Operations" },
  { term: "Cardinality", definition: "the number of unique values in a dataset or database column.", category: "PostgreSQL" },
  { term: "Check constraint", definition: "a database constraint that limits the values that can be stored in a column by checking them against a specified condition.", category: "PostgreSQL" },
  { term: "Chunk", definition: "a horizontal partition of a hypertable that contains data for a specific time interval and space partition.", category: "TimescaleDB" },
  { term: "Chunk interval", definition: "the time period covered by each chunk in a hypertable, which affects query performance and storage efficiency.", category: "TimescaleDB" },
  { term: "Chunk skipping", definition: "a query optimization technique that skips chunks not relevant to the query’s time range, dramatically improving performance.", category: "TimescaleDB" },
  { term: "CIDR (Classless Inter-Domain Routing)", definition: "a method for allocating IP addresses and routing IP packets.", category: "Security" },
  { term: "Client credentials", definition: "authentication tokens used by applications to access services programmatically without user interaction.", category: "Security" },
  { term: "Close", definition: "in financial data, the closing price of a security at the end of a trading period.", category: "Time-series" },
  { term: "Cloud", definition: "computing services delivered over the internet, including servers, storage, databases, networking, software, analytics, and intelligence.", category: "Cloud" },
  { term: "Cloud deployment", definition: "the use of public, private, or hybrid cloud infrastructure to host TimescaleDB, enabling elastic scalability and managed services.", category: "Cloud" },
  { term: "Cloud-native", definition: "an approach to building applications that leverage cloud infrastructure, scalability, and services like Kubernetes.", category: "Cloud" },
  { term: "Cold storage", definition: "a tier of data storage for infrequently accessed data that offers lower costs but higher access times.", category: "Storage" },
  { term: "Columnar", definition: "a data storage format that stores data column by column rather than row by row, optimizing for analytical queries.", category: "Storage" },
  { term: "Columnstore", definition: "TimescaleDB‘s columnar storage engine optimized for analytical workloads and compression.", category: "TimescaleDB" },
  { term: "Compression", definition: "the process of reducing data size by encoding information using fewer bits, improving storage efficiency and query performance.", category: "Storage" },
  { term: "Connection pooling", definition: "a technique for managing multiple database connections efficiently, reducing overhead for high-concurrency environments.", category: "Operations" },
  { term: "Consensus algorithm", definition: "protocols ensuring distributed systems agree on data state, critical for multi-node database deployments.", category: "Operations" },
  { term: "Compression policy", definition: "an automated rule that compresses hypertable chunks after they reach a specified age or size threshold.", category: "TimescaleDB" },
  { term: "Compression ratio", definition: "the ratio between the original data size and the compressed data size, indicating compression effectiveness.", category: "Storage" },
  { term: "Constraint", definition: "a rule enforced by the database to maintain data integrity and consistency.", category: "PostgreSQL" },
  { term: "Continuous aggregate", definition: "a materialized view that incrementally updates with new data, providing fast access to pre-computed aggregations.", category: "TimescaleDB" },
  { term: "Counter aggregation", definition: "aggregating monotonic counter data, handling counter resets and extrapolation.", category: "Time-series" },
  { term: "Cron", definition: "a time-based job scheduler in Unix-like computer operating systems.", category: "Operations" },
  { term: "Cross-region backup", definition: "a backup stored in a different geographical region from the primary data for disaster recovery.", category: "Operations" },
  { term: "Data lake", definition: "a centralized repository storing structured and unstructured data at scale, often integrated with time-series databases for analytics.", category: "Data & migration" },
  { term: "Data lineage", definition: "the tracking of data flow from source to destination, including transformations, essential for compliance and debugging.", category: "Data & migration" },
  { term: "Data pipeline", definition: "automated workflows for moving, transforming, and loading data between systems, often using tools like Apache Kafka or Apache Airflow.", category: "Data & migration" },
  { term: "Data migration", definition: "the process of moving data from one system, storage type, or format to another.", category: "Data & migration" },
  { term: "Data retention", definition: "the practice of storing data for a specified period before deletion, often governed by compliance requirements or storage optimization.", category: "Operations" },
  { term: "Data rollup", definition: "the process of summarizing detailed historical data into higher-level aggregates, balancing storage needs with query efficiency.", category: "Time-series" },
  { term: "Data skew", definition: "uneven distribution of data across partitions or nodes, potentially causing performance bottlenecks.", category: "Data & migration" },
  { term: "Data tiering", definition: "a storage management strategy that places data on different storage tiers based on access patterns and performance requirements.", category: "Storage" },
  { term: "Data type", definition: "a classification that specifies which type of value a variable can hold, such as integer, string, or boolean.", category: "PostgreSQL" },
  { term: "Decompress", definition: "the process of restoring compressed data to its original, uncompressed state.", category: "Storage" },
  { term: "Delta", definition: "the difference between two values, commonly used in counter aggregations to calculate the change over time.", category: "Time-series" },
  { term: "DHCP (Dynamic Host Configuration Protocol)", definition: "a network management protocol used to automatically assign IP addresses and other network configuration parameters.", category: "Security" },
  { term: "Dimension", definition: "a partitioning key in a hypertable that determines how data is distributed across chunks.", category: "TimescaleDB" },
  { term: "Disaster recovery", definition: "the process and procedures for recovering and protecting a business’s IT infrastructure in the event of a disaster.", category: "Operations" },
  { term: "Double precision", definition: "a floating-point data type that provides more precision than the standard float type.", category: "PostgreSQL" },
  { term: "Downsample", definition: "the process of reducing the temporal resolution of time-series data by aggregating data points over longer time intervals.", category: "Time-series" },
  { term: "Downtime", definition: "the period during which a system, service, or application is unavailable or not operational.", category: "Operations" },
  { term: "Dual-write and backfill", definition: "a migration approach where new data is written to both the source and target databases simultaneously, followed by backfilling historical data to ensure completeness.", category: "Data & migration" },
  { term: "Dual-write", definition: "a migration pattern where applications write data to both the source and target systems simultaneously.", category: "Data & migration" },
  { term: "Edge computing", definition: "processing data at or near the data source such as IoT devices, rather than solely in centralized servers, reducing latency.", category: "Cloud" },
  { term: "Edge gateway", definition: "a device that aggregates data from sensors and performs preprocessing before sending data to cloud or centralized databases.", category: "Cloud" },
  { term: "ELT (Extract, Load, Transform)", definition: "a data pipeline pattern where raw data is loaded first, then transformed within the target system, leveraging database processing power.", category: "Data & migration" },
  { term: "Embedding", definition: "a vector representation of data such as text or images, that captures semantic meaning in a high-dimensional space.", category: "AI & vectors" },
  { term: "Error rate", definition: "the percentage of requests or operations that result in errors over a given time period.", category: "Observability" },
  { term: "Euclidean distance", definition: "a measure of the straight-line distance between two points in multidimensional space.", category: "AI & vectors" },
  { term: "Exactly-once", definition: "a message is delivered and processed precisely once. There is no loss and no duplicates.", category: "Data & migration" },
  { term: "Explain", definition: "a PostgreSQL command that shows the execution plan for a query, useful for performance analysis.", category: "PostgreSQL" },
  { term: "Event sourcing", definition: "an architectural pattern storing all changes as a sequence of events, naturally fitting time-series database capabilities.", category: "Time-series" },
  { term: "Event-driven architecture", definition: "a design pattern where components react to events such as sensor readings, requiring real-time data pipelines and storage.", category: "Data & migration" },
  { term: "Extension", definition: "a PostgreSQL add-on that extends the database’s functionality beyond the core features.", category: "PostgreSQL" },
  { term: "Fact table", definition: "the central table in a star schema containing quantitative measures, often time-series data with foreign keys to dimension tables.", category: "PostgreSQL" },
  { term: "Failover", definition: "the automatic switching to a backup system, server, or network upon the failure or abnormal termination of the primary system.", category: "Operations" },
  { term: "Financial time-series", definition: "high-volume, timestamped datasets like stock market feeds or trade logs, requiring low-latency, scalable databases like TimescaleDB.", category: "Time-series" },
  { term: "Foreign key", definition: "a database constraint that establishes a link between data in two tables by referencing the primary key of another table.", category: "PostgreSQL" },
  { term: "Fork", definition: "a copy of a database service that shares the same data but can diverge independently through separate writes.", category: "Cloud" },
  { term: "Free service", definition: "a free instance of Tiger Cloud with limited resources. You can create up to two free services under any pricing plan. When a free service reaches the resource limit, it converts to the read-only state. You can convert a free service to a standard one under paid pricing plans.", category: "Cloud" },
  { term: "FTP (File Transfer Protocol)", definition: "a standard network protocol used for transferring files between a client and server on a computer network.", category: "Security" },
  { term: "Gap filling", definition: "a technique for handling missing data points in time-series by interpolation or other methods, often implemented with hyperfunctions.", category: "Time-series" },
  { term: "GIN (Generalized Inverted Index)", definition: "a PostgreSQL index type designed for indexing composite values and supporting fast searches.", category: "PostgreSQL" },
  { term: "GiST (Generalized Search Tree)", definition: "a PostgreSQL index type that provides a framework for implementing custom index types.", category: "PostgreSQL" },
  { term: "GP-LTTB", definition: "an advanced downsampling algorithm that extends Largest-Triangle-Three-Buckets with Gaussian Process modeling.", category: "Time-series" },
  { term: "GUC (Grand Unified Configuration)", definition: "PostgreSQL‘s configuration parameter system that controls various aspects of database behavior.", category: "PostgreSQL" },
  { term: "GUID (Globally Unique Identifier)", definition: "a unique identifier used in software applications, typically represented as a 128-bit value.", category: "PostgreSQL" },
  { term: "Hash", definition: "an index type that provides constant-time lookups for equality comparisons but doesn’t support range queries.", category: "PostgreSQL" },
  { term: "High-cardinality", definition: "refers to datasets with a large number of unique values, which can strain storage and indexing in time-series applications.", category: "Time-series" },
  { term: "Histogram bucket", definition: "a predefined range of metrics organized for statistical analysis, commonly visualized in monitoring tools.", category: "Observability" },
  { term: "Hot standby", definition: "a replication configuration where the standby server can serve read-only queries while staying synchronized with the primary.", category: "Operations" },
  { term: "High availability", definition: "a system design that ensures an agreed level of operational performance, usually uptime, for a higher than normal period.", category: "Operations" },
  { term: "High", definition: "in financial data, the highest price of a security during a specific time period.", category: "Time-series" },
  { term: "Histogram", definition: "a graphical representation of the distribution of numerical data, showing the frequency of data points in different ranges.", category: "Observability" },
  { term: "Historical data", definition: "previously recorded data that provides context and trends for analysis and decision-making.", category: "Time-series" },
  { term: "HNSW (Hierarchical Navigable Small World)", definition: "a graph-based algorithm for approximate nearest neighbor search in high-dimensional spaces.", category: "AI & vectors" },
  { term: "Hot storage", definition: "a tier of data storage for frequently accessed data that provides the fastest access times but at higher cost.", category: "Storage" },
  { term: "Hypercore", definition: "TimescaleDB‘s hybrid storage engine that seamlessly combines row and column storage for optimal performance.", category: "TimescaleDB" },
  { term: "Hyperfunction", definition: "an SQL function in TimescaleDB designed for time-series analysis, statistics, and specialized computations.", category: "TimescaleDB" },
  { term: "HyperLogLog", definition: "a probabilistic data structure used for estimating the cardinality of large datasets with minimal memory usage.", category: "PostgreSQL" },
  { term: "Hypershift", definition: "a migration tool and strategy for moving data to TimescaleDB with minimal downtime.", category: "Data & migration" },
  { term: "Hypertable", definition: "TimescaleDB‘s core abstraction that automatically partitions time-series data for scalability.", category: "TimescaleDB" },
  { term: "Idempotency", definition: "the property where repeated operations produce the same result, crucial for reliable data ingestion and processing.", category: "Data & migration" },
  { term: "Ingest rate", definition: "the speed at which new data is written to the system, measured in rows per second. Critical for IoT and observability.", category: "Observability" },
  { term: "Inner product", definition: "a mathematical operation that combines two vectors to produce a scalar, used in similarity calculations.", category: "AI & vectors" },
  { term: "Insert", definition: "an SQL operation that adds new rows of data to a database table.", category: "PostgreSQL" },
  { term: "Integer", definition: "a data type that represents whole numbers without decimal points.", category: "PostgreSQL" },
  { term: "Intercept", definition: "a statistical measure representing the y-intercept in linear regression analysis.", category: "Time-series" },
  { term: "Internet gateway", definition: "an AWS VPC component that enables communication between instances in a VPC and the internet.", category: "Cloud" },
  { term: "Interpolation", definition: "a method of estimating unknown values that fall between known data points.", category: "Time-series" },
  { term: "IP allow list", definition: "a security feature that restricts access to specified IP addresses or ranges.", category: "Security" },
  { term: "Isolation level", definition: "a database transaction property that defines the degree to which operations in one transaction are isolated from those in other concurrent transactions.", category: "PostgreSQL" },
  { term: "Job", definition: "an automated task scheduled to run at specific intervals or triggered by certain conditions.", category: "Operations" },
  { term: "Job execution", definition: "the process of running scheduled background tasks or automated procedures.", category: "Operations" },
  { term: "JIT (Just-In-Time) compilation", definition: "PostgreSQL feature that compiles frequently executed query parts for improved performance, available in TimescaleDB.", category: "PostgreSQL" },
  { term: "Job history", definition: "a record of past job executions, including their status, duration, and any errors encountered.", category: "Operations" },
  { term: "JSON (JavaScript Object Notation)", definition: "a lightweight data interchange format that is easy for humans to read and write.", category: "PostgreSQL" },
  { term: "JWT (JSON Web Token)", definition: "a compact, URL-safe means of representing claims to be transferred between two parties.", category: "Security" },
  { term: "Latency", definition: "the time delay between a request being made and the response being received.", category: "Observability" },
  { term: "Lifecycle policy", definition: "a set of rules that automatically manage data throughout its lifecycle, including retention and deletion.", category: "Operations" },
  { term: "Live migration", definition: "a data migration technique that moves data with minimal or zero downtime.", category: "Data & migration" },
  { term: "Load balancer", definition: "a service distributing traffic across servers or database nodes to optimize resource use and avoid single points of failure.", category: "Operations" },
  { term: "Log-Structured Merge (LSM) Tree", definition: "a data structure optimized for write-heavy workloads, though TimescaleDB primarily uses B-tree indexes for balanced read/write performance.", category: "PostgreSQL" },
  { term: "LlamaIndex", definition: "a framework for building applications with large language models, providing tools for data ingestion and querying.", category: "AI & vectors" },
  { term: "LOCF (Last Observation Carried Forward)", definition: "a method for handling missing data by using the most recent known value.", category: "Time-series" },
  { term: "Logical backup", definition: "a backup method that exports data in a human-readable format, allowing for selective restoration.", category: "Operations" },
  { term: "Logical replication", definition: "a PostgreSQL feature that replicates data changes at the logical level rather than the physical level.", category: "Operations" },
  { term: "Logging", definition: "the process of recording events, errors, and system activities for monitoring and troubleshooting purposes.", category: "Observability" },
  { term: "Low", definition: "in financial data, the lowest price of a security during a specific time period.", category: "Time-series" },
  { term: "LTTB (Largest-Triangle-Three-Buckets)", definition: "a downsampling algorithm that preserves the visual characteristics of time-series data.", category: "Time-series" },
  { term: "Manhattan distance", definition: "a distance metric calculated as the sum of the absolute differences of their coordinates.", category: "AI & vectors" },
  { term: "Manual compression", definition: "the process of compressing chunks manually rather than through automated policies.", category: "Storage" },
  { term: "Materialization", definition: "the process of computing and storing the results of a query or view for faster access.", category: "PostgreSQL" },
  { term: "Materialized view", definition: "a database object that stores the result of a query and can be refreshed periodically.", category: "PostgreSQL" },
  { term: "Memory-optimized query", definition: "a query pattern designed to minimize disk I/O by leveraging available RAM and efficient data structures.", category: "PostgreSQL" },
  { term: "Metric", definition: "a quantitative measurement used to assess system performance, business outcomes, or operational efficiency.", category: "Observability" },
  { term: "MFA (Multi-Factor Authentication)", definition: "a security method that requires two or more verification factors to grant access.", category: "Security" },
  { term: "Migration", definition: "the process of moving data, applications, or systems from one environment to another.", category: "Data & migration" },
  { term: "Monitoring", definition: "the continuous observation and measurement of system performance and health.", category: "Observability" },
  { term: "Multi-tenancy", definition: "an architecture pattern supporting multiple customers or applications within a single database instance, with proper isolation.", category: "Cloud" },
  { term: "MQTT (Message Queuing Telemetry Transport)", definition: "a lightweight messaging protocol designed for small sensors and mobile devices.", category: "Data & migration" },
  { term: "MST (Managed Service for TimescaleDB)", definition: "a fully managed TimescaleDB service that handles infrastructure and maintenance tasks.", category: "Cloud" },
  { term: "NAT Gateway", definition: "a network address translation service that enables instances in a private subnet to connect to the internet.", category: "Cloud" },
  { term: "Node (database node)", definition: "an individual server within a distributed system, contributing to storage, compute, or replication tasks.", category: "Operations" },
  { term: "Normalization", definition: "database design technique organizing data to reduce redundancy, though time-series data often benefits from denormalized structures.", category: "PostgreSQL" },
  { term: "Not null", definition: "a database constraint that ensures a column cannot contain empty values.", category: "PostgreSQL" },
  { term: "Numeric", definition: "a PostgreSQL data type for storing exact numeric values with user-defined precision.", category: "PostgreSQL" },
  { term: "OAuth", definition: "an open standard for access delegation commonly used for token-based authentication and authorization.", category: "Security" },
  { term: "Observability", definition: "the ability to measure the internal states of a system by examining its outputs.", category: "Observability" },
  { term: "OLAP (Online Analytical Processing)", definition: "systems or workloads focused on large-scale, multidimensional, and complex analytical queries.", category: "Data & migration" },
  { term: "OLTP (Online Transaction Processing)", definition: "high-speed transactional systems optimized for data inserts, updates, and short queries.", category: "Data & migration" },
  { term: "OHLC", definition: "an acronym for Open, High, Low, Close prices, commonly used in financial data analysis.", category: "Time-series" },
  { term: "OHLCV", definition: "an extension of OHLC that includes Volume data for complete candlestick analysis.", category: "Time-series" },
  { term: "Open", definition: "in financial data, the opening price of a security at the beginning of a trading period.", category: "Time-series" },
  { term: "OpenTelemetry", definition: "open standard for collecting, processing, and exporting telemetry data, often stored in time-series databases.", category: "Observability" },
  { term: "Optimization", definition: "the process of making systems, queries, or operations more efficient and performant.", category: "PostgreSQL" },
  { term: "Parallel copy", definition: "a technique for copying large amounts of data using multiple concurrent processes to improve performance.", category: "Data & migration" },
  { term: "Parallel Query Execution", definition: "a PostgreSQL feature that uses multiple CPU cores to execute single queries faster, inherited by TimescaleDB.", category: "PostgreSQL" },
  { term: "Partitioning", definition: "the practice of dividing large tables into smaller, more manageable pieces based on certain criteria.", category: "PostgreSQL" },
  { term: "Percentile", definition: "a statistical measure that indicates the value below which a certain percentage of observations fall.", category: "Time-series" },
  { term: "Performance", definition: "a measure of how efficiently a system operates, often quantified by metrics like throughput, latency, and resource utilization.", category: "Observability" },
  { term: "pg\\_basebackup", definition: "a PostgreSQL utility for taking base backups of a running PostgreSQL cluster.", category: "Operations" },
  { term: "pg\\_dump", definition: "a PostgreSQL utility for backing up database objects and data in various formats.", category: "Operations" },
  { term: "pg\\_restore", definition: "a PostgreSQL utility for restoring databases from backup files created by `pg_dump`.", category: "Operations" },
  { term: "pgVector", definition: "a PostgreSQL extension that adds vector similarity search capabilities for AI and machine learning applications.", category: "AI & vectors" },
  { term: "pgai on Tiger Cloud", definition: "a cloud solution for building search, RAG, and AI agents with PostgreSQL. Enables calling AI embedding and generation models directly from the database using SQL.", category: "AI & vectors" },
  { term: "pgvectorscale", definition: "a performance enhancement for pgvector featuring StreamingDiskANN indexing, binary quantization compression, and label-based filtering.", category: "AI & vectors" },
  { term: "pgvectorizer", definition: "a TimescaleDB tool for automatically vectorizing and indexing data for similarity search.", category: "AI & vectors" },
  { term: "Physical backup", definition: "a backup method that copies the actual database files at the storage level.", category: "Operations" },
  { term: "PITR (Point-in-Time Recovery)", definition: "the ability to restore a database to a specific moment in time.", category: "Operations" },
  { term: "Policy", definition: "an automated rule or procedure that performs maintenance tasks like compression, retention, or refresh operations.", category: "TimescaleDB" },
  { term: "Predictive maintenance", definition: "the use of time-series data to forecast equipment failure, common in IoT and industrial applications.", category: "Time-series" },
  { term: "PostgreSQL", definition: "an open-source object-relational database system known for its reliability, robustness, and performance.", category: "PostgreSQL" },
  { term: "PostGIS", definition: "a PostgreSQL extension that adds support for geographic objects and spatial queries.", category: "PostgreSQL" },
  { term: "Primary key", definition: "a database constraint that uniquely identifies each row in a table.", category: "PostgreSQL" },
  { term: "psql", definition: "an interactive terminal-based front-end to PostgreSQL that allows users to type queries interactively.", category: "PostgreSQL" },
  { term: "QPS (Queries Per Second)", definition: "a measure of database performance indicating how many queries a database can process per second.", category: "Observability" },
  { term: "Query", definition: "a request for data or information from a database, typically written in SQL.", category: "PostgreSQL" },
  { term: "Query performance", definition: "a measure of how efficiently database queries execute, including factors like execution time and resource usage.", category: "PostgreSQL" },
  { term: "Query planner/optimizer", definition: "a component determining the most efficient strategy for executing SQL queries based on database structure and indexes.", category: "PostgreSQL" },
  { term: "Query planning", definition: "the database process of determining the most efficient way to execute a query.", category: "PostgreSQL" },
  { term: "RBAC (Role-Based Access Control)", definition: "a security model that assigns permissions to users based on their roles within an organization.", category: "Security" },
  { term: "Read committed", definition: "an isolation level where transactions can read committed changes made by other transactions.", category: "PostgreSQL" },
  { term: "Read scaling", definition: "a technique for improving database performance by distributing read queries across multiple database replicas.", category: "Operations" },
  { term: "Read uncommitted", definition: "the lowest isolation level where transactions can read uncommitted changes from other transactions.", category: "PostgreSQL" },
  { term: "Read-only role", definition: "a database role with permissions limited to reading data without modification capabilities.", category: "Security" },
  { term: "Read replica", definition: "a copy of the primary database that serves read-only queries, improving read scalability and geographic distribution.", category: "Operations" },
  { term: "Real-time analytics", definition: "the immediate analysis of incoming data streams, crucial for observability, trading platforms, and IoT monitoring.", category: "Time-series" },
  { term: "Real", definition: "a PostgreSQL data type for storing single-precision floating-point numbers.", category: "PostgreSQL" },
  { term: "Real-time aggregate", definition: "a continuous aggregate that includes both materialized historical data and real-time calculations on recent data.", category: "TimescaleDB" },
  { term: "Refresh policy", definition: "an automated rule that determines when and how continuous aggregates are updated with new data.", category: "TimescaleDB" },
  { term: "Region", definition: "a geographical area containing multiple data centers, used in cloud computing for data locality and compliance.", category: "Cloud" },
  { term: "Repeatable read", definition: "an isolation level that ensures a transaction sees a consistent snapshot of data throughout its execution.", category: "PostgreSQL" },
  { term: "Replica", definition: "a copy of a database that can be used for read scaling, backup, or disaster recovery purposes.", category: "Operations" },
  { term: "Replication", definition: "the process of copying and maintaining data across multiple database instances to ensure availability and durability.", category: "Operations" },
  { term: "Response time", definition: "the time it takes for a system to respond to a request, measured from request initiation to response completion.", category: "Observability" },
  { term: "REST API", definition: "a web service architecture that uses HTTP methods to enable communication between applications.", category: "Data & migration" },
  { term: "Restore", definition: "the process of recovering data from backups to restore a database to a previous state.", category: "Operations" },
  { term: "Restore point", definition: "a snapshot of database state that can be used as a reference point for recovery operations.", category: "Operations" },
  { term: "Retention policy", definition: "an automated rule that determines how long data is kept before being deleted from the system.", category: "TimescaleDB" },
  { term: "Route table", definition: "a set of rules that determine where network traffic is directed within a cloud network.", category: "Cloud" },
  { term: "RTO (Recovery Time Objective)", definition: "the maximum acceptable time that systems can be down after a failure or disaster.", category: "Operations" },
  { term: "RPO (Recovery Point Objective)", definition: "the maximum acceptable amount of data loss measured in time after a failure or disaster.", category: "Operations" },
  { term: "Rowstore", definition: "traditional row-oriented data storage where data is stored row by row, optimized for transactional workloads.", category: "Storage" },
  { term: "SAML (Security Assertion Markup Language)", definition: "an XML-based standard for exchanging authentication and authorization data between security domains.", category: "Security" },
  { term: "Scheduled job", definition: "an automated task that runs at predetermined times or intervals.", category: "Operations" },
  { term: "Schema evolution", definition: "the process of modifying database structure over time while maintaining compatibility with existing applications.", category: "PostgreSQL" },
  { term: "Schema", definition: "the structure of a database, including tables, columns, relationships, and constraints.", category: "PostgreSQL" },
  { term: "Security group", definition: "a virtual firewall that controls inbound and outbound traffic for cloud resources.", category: "Cloud" },
  { term: "Service discovery", definition: "mechanisms allowing applications to dynamically locate services like database endpoints, often used in distributed environments.", category: "Cloud" },
  { term: "Segmentwise recompression", definition: "a TimescaleDB compression technique that recompresses data segments to improve compression ratios.", category: "TimescaleDB" },
  { term: "Serializable", definition: "the highest isolation level that ensures transactions appear to run serially even when executed concurrently.", category: "PostgreSQL" },
  { term: "Tiger Cloud service", definition: "an optimized PostgreSQL instance extended with database engine innovations such as TimescaleDB, in a cloud infrastructure that delivers speed without sacrifice.", category: "Cloud" },
  { term: "Sharding", definition: "horizontal partitioning of data across multiple database instances, distributing load and enabling linear scalability.", category: "Data & migration" },
  { term: "SFTP (SSH File Transfer Protocol)", definition: "a secure version of FTP that encrypts both commands and data during transmission.", category: "Security" },
  { term: "SkipScan", definition: "query optimization for DISTINCT operations that incrementally jumps between ordered values without reading intermediate rows. Uses a Custom Scan node to efficiently traverse ordered indexes, dramatically improving performance over traditional DISTINCT queries.", category: "TimescaleDB" },
  { term: "Similarity search", definition: "a technique for finding items that are similar to a given query item, often used with vector embeddings.", category: "AI & vectors" },
  { term: "SLA (Service Level Agreement)", definition: "a contract that defines the expected level of service between a provider and customer.", category: "Operations" },
  { term: "SLI (Service Level Indicator)", definition: "a quantitative measure of some aspect of service quality.", category: "Observability" },
  { term: "SLO (Service Level Objective)", definition: "a target value or range for service quality measured by an SLI.", category: "Observability" },
  { term: "Slope", definition: "a statistical measure representing the rate of change in linear regression analysis.", category: "Time-series" },
  { term: "SMTP (Simple Mail Transfer Protocol)", definition: "an internet standard for email transmission across networks.", category: "Security" },
  { term: "Snapshot", definition: "a point-in-time copy of data that can be used for backup and recovery purposes.", category: "Operations" },
  { term: "SP-GiST (Space-Partitioned Generalized Search Tree)", definition: "a PostgreSQL index type for data structures that naturally partition search spaces.", category: "PostgreSQL" },
  { term: "Storage optimization", definition: "techniques for reducing storage costs and improving performance through compression, tiering, and efficient data organization.", category: "Storage" },
  { term: "Streaming data", definition: "continuous flows of data generated by devices, logs, or sensors, requiring high-ingest, real-time storage solutions.", category: "Time-series" },
  { term: "SQL (Structured Query Language)", definition: "a programming language designed for managing and querying relational databases.", category: "PostgreSQL" },
  { term: "SSH (Secure Shell)", definition: "a cryptographic network protocol for secure communication over an unsecured network.", category: "Security" },
  { term: "SSL (Secure Sockets Layer)", definition: "a security protocol that establishes encrypted links between networked computers.", category: "Security" },
  { term: "Standard service", definition: "a regular Tiger Cloud service that includes the resources and features according to the pricing plan. You can create standard services under any of the paid plans.", category: "Cloud" },
  { term: "Streaming replication", definition: "a PostgreSQL replication method that continuously sends write-ahead log records to standby servers.", category: "Operations" },
  { term: "Synthetic monitoring", definition: "simulated transactions or probes used to test system health, generating time-series metrics for performance analysis.", category: "Observability" },
  { term: "Table", definition: "a database object that stores data in rows and columns, similar to a spreadsheet.", category: "PostgreSQL" },
  { term: "Tablespace", definition: "a PostgreSQL storage structure that defines where database objects are physically stored on disk.", category: "PostgreSQL" },
  { term: "TCP (Transmission Control Protocol)", definition: "a connection-oriented protocol that ensures reliable data transmission between applications.", category: "Security" },
  { term: "TDigest", definition: "a probabilistic data structure for accurate estimation of percentiles in distributed systems.", category: "Time-series" },
  { term: "Telemetry", definition: "the collection of real-time data from systems or devices for monitoring and analysis.", category: "Observability" },
  { term: "Text", definition: "a PostgreSQL data type for storing variable-length character strings.", category: "PostgreSQL" },
  { term: "Throughput", definition: "a measure of system performance indicating the amount of work performed or data processed per unit of time.", category: "Observability" },
  { term: "Tiered storage", definition: "a storage strategy that automatically moves data between different storage classes based on access patterns and age.", category: "Storage" },
  { term: "Tiger Cloud", definition: "Tiger Data ‘s managed cloud platform that provides TimescaleDB as a fully managed solution with additional features.", category: "Cloud" },
  { term: "Tiger Lake", definition: "Tiger Data ‘s service for integrating operational databases with data lake architectures.", category: "Cloud" },
  { term: "Tiger Cloud service", definition: "an optimized PostgreSQL instance extended with database engine innovations such as TimescaleDB, in a cloud infrastructure that delivers speed without sacrifice.", category: "Cloud" },
  { term: "Time series", definition: "data points indexed and ordered by time, typically representing how values change over time.", category: "Time-series" },
  { term: "Time-weighted average", definition: "a statistical calculation that gives more weight to values based on the duration they were held.", category: "Time-series" },
  { term: "Time bucketing", definition: "grouping timestamps into uniform intervals for analysis, commonly used with hyperfunctions.", category: "Time-series" },
  { term: "Time-series forecasting", definition: "the application of statistical models to time-series data to predict future trends or events.", category: "Time-series" },
  { term: "TimescaleDB", definition: "an open-source PostgreSQL extension for real-time analytics that provides scalability and performance optimizations.", category: "TimescaleDB" },
  { term: "Timestamp", definition: "a data type that stores date and time information without timezone data.", category: "PostgreSQL" },
  { term: "Timestamptz", definition: "a PostgreSQL data type that stores timestamp with timezone information.", category: "PostgreSQL" },
  { term: "TLS (Transport Layer Security)", definition: "a cryptographic protocol that provides security for communication over networks.", category: "Security" },
  { term: "Tombstone", definition: "marker indicating deleted data in append-only systems, requiring periodic cleanup processes.", category: "Storage" },
  { term: "Transaction isolation", definition: "the database property controlling the visibility of uncommitted changes between concurrent transactions.", category: "PostgreSQL" },
  { term: "TPS (Transactions Per Second)", definition: "a measure of database performance indicating transaction processing capacity.", category: "Observability" },
  { term: "Transaction", definition: "a unit of work performed against a database that must be completed entirely or not at all.", category: "PostgreSQL" },
  { term: "Trigger", definition: "a database procedure that automatically executes in response to certain events on a table or view.", category: "PostgreSQL" },
  { term: "UDP (User Datagram Protocol)", definition: "a connectionless communication protocol that provides fast but unreliable data transmission.", category: "Security" },
  { term: "Unique", definition: "a database constraint that ensures all values in a column or combination of columns are distinct.", category: "PostgreSQL" },
  { term: "Uptime", definition: "the amount of time that a system has been operational and available for use.", category: "Observability" },
  { term: "Usage-based storage", definition: "a billing model where storage costs are based on actual data stored rather than provisioned capacity.", category: "Cloud" },
  { term: "UUID (Universally Unique Identifier)", definition: "a 128-bit identifier used to uniquely identify information without central coordination.", category: "PostgreSQL" },
  { term: "Vacuum", definition: "a PostgreSQL maintenance operation that reclaims storage and updates database statistics.", category: "PostgreSQL" },
  { term: "Varchar", definition: "a variable-length character data type that can store strings up to a specified maximum length.", category: "PostgreSQL" },
  { term: "Vector operations", definition: "SIMD (Single Instruction, Multiple Data) optimizations for processing arrays of data, improving analytical query performance.", category: "AI & vectors" },
  { term: "Vertical scaling (scale up)", definition: "increasing system capacity by adding more power (CPU, RAM) to existing machines, as opposed to horizontal scaling.", category: "Operations" },
  { term: "Visualization tool", definition: "a platform or dashboard used to display time-series data in charts, graphs, and alerts for easier monitoring and analysis.", category: "Observability" },
  { term: "Vector", definition: "a mathematical object with magnitude and direction, used in machine learning for representing data as numerical arrays.", category: "AI & vectors" },
  { term: "VPC (Virtual Private Cloud)", definition: "a virtual network dedicated to your cloud account that provides network isolation.", category: "Cloud" },
  { term: "VWAP (Volume Weighted Average Price)", definition: "a financial indicator that shows the average price weighted by volume over a specific time period.", category: "Time-series" },
  { term: "WAL (Write-Ahead Log)", definition: "PostgreSQL‘s method for ensuring data integrity by writing changes to a log before applying them to data files.", category: "PostgreSQL" },
  { term: "Warm storage", definition: "a storage tier that balances access speed and cost, suitable for data accessed occasionally.", category: "Storage" },
  { term: "Watermark", definition: "a timestamp that tracks the progress of continuous aggregate materialization.", category: "TimescaleDB" },
  { term: "WebSocket", definition: "a communication protocol that provides full-duplex communication channels over a single TCP connection.", category: "Data & migration" },
  { term: "Window function", definition: "an SQL function that performs calculations across related rows, particularly useful for time-series analytics and trend analysis.", category: "PostgreSQL" },
  { term: "Workload management", definition: "techniques for prioritizing and scheduling different types of database operations to optimize overall system performance.", category: "Operations" },
  { term: "XML (eXtensible Markup Language)", definition: "a markup language that defines rules for encoding documents in a format that is both human-readable and machine-readable.", category: "PostgreSQL" },
  { term: "YAML (YAML Ain’t Markup Language)", definition: "a human-readable data serialization standard commonly used for configuration files.", category: "PostgreSQL" },
  { term: "Zero downtime", definition: "a system design goal where services remain available during maintenance, upgrades, or migrations without interruption.", category: "Operations" },
  { term: "Zero-downtime migration", definition: "migration strategies that maintain service availability throughout the transition process, often using techniques like dual-write and gradual cutover.", category: "Data & migration" },
];

export const categories = ["TimescaleDB", "Storage", "Time-series", "Cloud", "Security", "Operations", "Observability", "AI & vectors", "PostgreSQL", "Data & migration"];

/** URL-safe id for a term (for anchor links and "On this page" TOC). */
export function slug(term: string): string {
  return term
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[()]/g, "")
    .replace(/[/,]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}
