packages:
  - .

allowBuilds:
  '@sentry/cli': true
  esbuild: false
  sharp: false

ignoredBuiltDependencies:
  - esbuild
  - protobufjs
  - sharp

patchedDependencies:
  starlight-llms-txt@0.8.0: patches/starlight-llms-txt@0.8.0.patch
  vite@7.3.1: patches/vite@7.3.1.patch
