#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# TimescaleDB Daily Change Summarizer
# This script monitors the TimescaleDB repository for merged features and uses AI (Claude)
# to generate documentation-ready summaries for technical writers.
#
# Dependencies:
# - anthropic=="0.*" (Anthropic SDK for Python)
# - GitHub CLI (gh) must be installed and authenticated in the environment.
#
import argparse
import logging
import os
import sys
import subprocess
import json
import time

# Configure standard logging to output timestamps and log levels.
logging.basicConfig(format='%(asctime)s %(levelname)s: %(message)s', level=logging.INFO)

def main():
    # Define command-line arguments.
    parser = argparse.ArgumentParser(description='Update API references from TimescaleDB source.')
    # The script expects a file containing a list of PRs, usually generated by 'gh pr list'.
    parser.add_argument('--pr-file', type=str, help='Path to the file containing list of PRs')
    args = parser.parse_args()

    # Early exit if the PR file is missing or empty to avoid unnecessary processing.
    if not os.path.exists(args.pr_file) or os.path.getsize(args.pr_file) == 0:
        logging.info(f"No PRs found in {args.pr_file}. Bailing out.")
        sys.exit(0)
    
    logging.info(f"Processing PRs from {args.pr_file}")
    prs = []
    # Open the PR list file and extract the PR numbers.
    with open(args.pr_file, 'r') as f:
        for line in f:
            pr_info = line.strip()
            if not pr_info:
                continue
            # 'gh pr list' output typically uses tabs to separate fields.
            # We only need the first part, which is the PR number.
            parts = pr_info.split('\t')
            prs.append(parts[0])
    
    logging.info(f"Collected {len(prs)} pull requests to inspect.")
    
    # This list will store tuples of (PR number, list of fragment contents) for confirmed features.
    feature_prs = []
    
    # Iterate through each PR to determine if it contains user-facing features.
    for pr_number in prs:
        # Throttle requests slightly to be mindful of GitHub API rate limits.
        time.sleep(0.5)
        try:
            # Fetch specific JSON metadata for the PR using the GitHub CLI.
            cmd = [
                "gh", "pr", "view", pr_number,
                "--repo", "timescale/timescaledb",
                "--json", "baseRefName,state,files,mergeCommit"
            ]
            result = subprocess.run(cmd, capture_output=True, text=True, check=True)
            pr_data = json.loads(result.stdout)
        except subprocess.CalledProcessError as e:
            logging.error(f"Failed to fetch details for PR #{pr_number}: {e.stderr}")
            continue
        except json.JSONDecodeError:
            logging.error(f"Failed to parse JSON for PR #{pr_number}")
            continue

        # We only care about PRs that have been merged into the 'main' branch.
        if pr_data.get("state") != "MERGED" or pr_data.get("baseRefName") != "main":
            logging.info(f"#{pr_number} -> Skipping PR #{pr_number}: Not merged to 'main' (state: {pr_data.get('state')}, base: {pr_data.get('baseRefName')})")
            continue

        # Look for changelog fragments in the '.unreleased/' directory.
        # These fragments are YAML files that describe the change for release notes.
        files = pr_data.get("files", [])
        unreleased_files = [f.get("path") for f in files if f.get("path", "").startswith(".unreleased/")]
        
        # If no '.unreleased/' files are found, it's likely an internal or non-user-facing change.
        if not unreleased_files:
            logging.info(f"#{pr_number} -> Skipping PR #{pr_number}: No files in .unreleased/ directory")
            continue
            
        logging.info(f"#{pr_number} -> PR #{pr_number} meets all conditions. Proceeding with inspection logic.")
        
        # Determine the correct commit reference to fetch the file contents.
        # We prefer the merge commit SHA for accuracy.
        merge_commit_node = pr_data.get("mergeCommit")
        merge_commit = merge_commit_node.get("oid") if merge_commit_node else "main"

        is_feature = False
        unreleased_contents = []
        # Fetch and inspect the content of each '.unreleased/' file.
        for file_path in unreleased_files:
            # Use the GitHub API via 'gh' to get the raw file content.
            cmd = [
                "gh", "api", 
                "-H", "Accept: application/vnd.github.v3.raw", 
                f"/repos/timescale/timescaledb/contents/{file_path}?ref={merge_commit}"
            ]
            res = subprocess.run(cmd, capture_output=True, text=True)

            # Handle cases where the file might have been deleted in the PR itself.
            if res.returncode != 0:
                if "404" in res.stderr:
                    logging.info(f"#{pr_number} -> Ignoring deleted file: {file_path}")
                    continue
                else:
                    logging.error(f"Failed to fetch content for {file_path} in PR #{pr_number}: {res.stderr}")
                    continue

            # Store the fragment content for inclusion in the AI prompt later.
            unreleased_contents.append(f"File: {file_path}\nContent:\n{res.stdout}")
            # A keyword "Implements" in the fragment indicates it's a new feature or API addition.
            if any(line.startswith("Implements") for line in res.stdout.splitlines()):
                is_feature = True

        # If it's a confirmed feature, add it to our processing queue.
        if is_feature:
            feature_prs.append((pr_number, unreleased_contents))
            logging.info(f"#{pr_number} -> new feature, needs to be inspected.")

    # If no features were found after scanning all PRs, exit gracefully.
    if len(feature_prs) == 0:
        logging.info("No new features merged.")
        sys.exit(0)

    logging.info(f"reduced to {len(feature_prs)} pull requests to inspect.")

    # Attempt to initialize the Anthropic (Claude) client.
    try:
        import anthropic
    except ImportError:
        logging.error("The 'anthropic' library is required to call the Claude API. Run: pip install anthropic")
        sys.exit(1)

    # Initialize the client (expects ANTHROPIC_API_KEY environment variable).
    client = anthropic.Anthropic()
    
    # Process each confirmed feature PR with Claude.
    for pr_number, fragments in feature_prs:
        logging.info(f"Calling Claude API for PR #{pr_number}")
        
        try:
            # Fetch the PR title and body to provide broad context to the AI.
            cmd = ["gh", "pr", "view", pr_number, "--repo", "timescale/timescaledb", "--json", "title,body"]
            res = subprocess.run(cmd, capture_output=True, text=True, check=True)
            pr_data = json.loads(res.stdout)
            
            # Fetch the code diff to give the AI visibility into the actual code changes.
            cmd_diff = ["gh", "pr", "diff", pr_number, "--repo", "timescale/timescaledb"]
            res_diff = subprocess.run(cmd_diff, capture_output=True, text=True, check=True)
            # Truncate the diff to 10,000 characters to stay within reasonable token limits.
            diff_content = res_diff.stdout[:10000] 
            
            # Construct the full context block for the AI.
            pr_content = f"""
                Title: {pr_data.get('title')}
                Body: {pr_data.get('body')}

                Unreleased Fragments:
                {chr(10).join(fragments)}

                Code Diff (truncated):
                {diff_content}
            """
        except Exception as e:
            logging.error(f"Failed to fetch content for #{pr_number}: {e}")
            continue

        try:
            # Call the Claude API to generate a structured summary.
            response = client.messages.create(
                model="claude-sonnet-4-6", # Specifies the AI model to use.
                max_tokens=4098,
                messages=[
                    {
                        "role": "user",
                        "content": f"""
                            Role: You are a Senior Software Engineer briefing a Technical Writer on a recent Pull Request (PR).
                            Task: Analyze the provided PR description, unreleased fragments, and code diff to generate a structured summary that identifies exactly what needs to be updated in the external documentation.
                            
                            Input Data:
                            {pr_content}
                            
                            Tone: Professional, clear, and technical but accessible. Avoid jargon that isn't defined in the API spec.
                            Output Requirements:
                            1. High-Level Summary: A 2-3 sentence explanation of why this change was made and what user problem it solves.
                            2. API Specification Changes: 
                                * New Endpoints/Methods: List any additions.
                                * Modified Parameters: Highlight changed names, types, or default values.
                                * Deprecations: Explicitly flag any logic that is now "legacy."
                                * Breaking Changes: Clearly state if an existing integration will break.
                            3. Technical Nuances: Are there new error codes, rate limits, or required headers?
                            
                            Note: Do not attempt to access external URLs. Use only the provided information.
                        """
                    }
                ]
            )
            # Log the final summary generated by Claude.
            summary_text = response.content[0].text
            logging.info(f"#{pr_number} -> got the API response for PR")

            # Create a GitHub issue in Tiger-Data-Docs for each feature that needs documenting.
            # This fulfills the goal of automating the documentation hand-off.
            try:
                issue_title = f"Doc Update: TimescaleDB PR #{pr_number} - {pr_data.get('title')}"
                issue_body = f"""
                # {pr_data.get('title')}
                Source PR: [timescale/timescaledb#{pr_number}](https://github.com/timescale/timescaledb/pull/{pr_number})
                ---
                {summary_text}
                """
                logging.info(f"Creating GitHub issue: {issue_title}")
                # We use the GitHub CLI to create an issue in the current repository.
                subprocess.run([
                    "gh", "issue", "create",
                    "--title", issue_title,
                    "--body", issue_body,
                    "--repo", "timescale/Tiger-Data-Docs",
                    #"--label", "doc-correction-or-change"
                ], check=True)
            except subprocess.CalledProcessError as e:
                logging.error(f"Failed to create GitHub issue for PR #{pr_number}: {e}")
        except Exception as e:
            logging.error(f"Error calling Claude API for PR #{pr_number}: {e}")

if __name__ == "__main__":
    # Standard entry point for the script.
    main()
