# Issue template chooser for Tiger Data Docs
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

blank_issues_enabled: true

templates:
  - doc-feedback.md
  - doc-correction-or-change.md
  - changelog-request.md
