/**
 * Variable definitions for $VARIABLE substitution in markdown content.
 * Ported from the old docs repo (web-documentation/vars.js).
 *
 * Used by the remark-variables plugin at build time.
 */
const vars: Record<string, string> = {
  // General
  PRODUCT_PREFIX: "Tiger",
  COMPANY: "Tiger Data",
  COMPANY_URL: "https://www.tigerdata.com",
  PG: "Postgres",

  // Pricing
  PRICING_PLAN_CAP: "Pricing plan",
  PRICING_PLAN: "pricing plan",
  SCALE: "Scale",
  PERFORMANCE: "Performance",
  ENTERPRISE: "Enterprise",
  FREE: "Free",

  // Products
  CLOUD_LONG: "Tiger Cloud",
  LAKE_LONG: "Tiger Lake",
  LAKE_SHORT: "Tiger Lake",
  TIMESCALE_DB: "TimescaleDB",
  PRODUCTS_ALL: "Tiger Data products",
  PRODUCTS_CL_DB: "Tiger Cloud and TimescaleDB",
  TDB_APACHE: "TimescaleDB Apache 2 Edition",
  TDB_COMMUNITY: "TimescaleDB Community Edition",
  SELF_SHORT_CAP: "Self-hosted",
  SELF_SHORT: "self-hosted",
  SELF_LONG_CAP: "Self-hosted TimescaleDB",
  SELF_LONG: "self-hosted TimescaleDB",
  CONSOLE: "Tiger Console",
  CONSOLE_LONG: "Tiger Console",
  CONSOLE_SHORT: "Console",
  CLI_LONG: "Tiger CLI",
  CLI_SHORT: "CLI",
  REST_LONG: "Tiger REST API",
  REST_SHORT: "REST API",
  MCP_LONG: "Tiger MCP",
  MCP_SHORT: "Tiger MCP",
  AGENTS_LONG: "Tiger Agents for Work",
  AGENTS_SHORT: "Tiger Agent",
  AGENTS_CLI: "Tiger Agent CLI",
  EON_SHORT: "Eon",
  EON_LONG: "Tiger Eon",
  CONSOLE_URL: "https://console.cloud.timescale.com/",
  MST_LONG: "Managed Service for TimescaleDB",
  MST_SHORT: "MST",
  MST_CONSOLE_LONG: "Managed Service for TimescaleDB Console",
  MST_CONSOLE_SHORT: "MST Console",
  MST_CONSOLE_URL: "https://portal.managed.timescale.com/",
  POPSQL: "PopSQL",
  SQL_EDITOR: "SQL editor",
  CLOUD_EDITOR: "Tiger Cloud SQL editor",
  SQL_ASSISTANT_LONG: "Tiger Cloud SQL assistant",
  SQL_ASSISTANT_SHORT: "SQL assistant",
  POPSQL_URL: "https://popsql.com/",
  SKIPSCAN_LONG: "Tiger Data SkipScan",
  SKIPSCAN_SHORT: "SkipScan",
  TOOLKIT_LONG: "TimescaleDB Toolkit",
  TOOLKIT_SHORT: "Toolkit",
  PGAI_LONG: "pgai on Tiger Data",
  PGAI_SHORT: "pgai",
  PGVECTORSCALE: "pgvectorscale",
  PG_SPOT: "pgspot",

  // Projects
  PROJECT_LONG: "Tiger Cloud project",
  PROJECT_SHORT: "project",
  PROJECT_SHORT_CAP: "Project",
  ACCOUNT_LONG: "Tiger Cloud account",
  ACCOUNT_SHORT: "account",

  // Services
  TIGER_POSTGRES: "Tiger Cloud",
  SERVICE_LONG: "Tiger Cloud service",
  SERVICE_SHORT_CAP: "Service",
  SERVICE_SHORT: "service",
  MST_SERVICE_LONG: "Managed Service for TimescaleDB service",
  MST_SERVICE_SHORT: "MST service",

  // Features
  HYPERTABLE_CAP: "Hypertable",
  HYPERTABLE: "hypertable",
  HYPERCORE_CAP: "Hypercore",
  HYPERCORE: "hypercore",
  ROWSTORE_CAP: "Rowstore",
  ROWSTORE: "rowstore",
  COLUMNSTORE_CAP: "Columnstore",
  COLUMNSTORE: "columnstore",
  CHUNK_CAP: "Chunk",
  CHUNK: "chunk",
  CHUNK_SKIPPING_CAP: "Chunk skipping",
  CHUNK_SKIPPING: "chunk skipping",
  MAT_HYPERTABLE_CAP: "Materialized hypertable",
  MAT_HYPERTABLE: "materialized hypertable",
  CAGG_CAP: "Continuous aggregate",
  CAGG: "continuous aggregate",
  RTAGG_CAP: "Real-time aggregate",
  RTAGG: "real-time aggregate",
  TIME_BUCKET_CAP: "Time bucket",
  TIME_BUCKET: "time bucket",
  HA_REPLICA_CAP: "High-availability replica",
  HA_REPLICA: "high-availability replica",
  HA_REPLICA_SHORT: "HA replica",
  READ_REPLICA_CAP: "Read replica",
  READ_REPLICA: "read replica",
  JOB_CAP: "Job",
  JOB: "job",
  PAR_COPY_CAP: "Parallel copy",
  PAR_COPY: "parallel copy",
  PG_VECTORIZER: "PgVectorizer",
  DATA_MODE: "Data view",
  VPC: "VPC",
  IO_BOOST: "I/O boost",
  PG_CONNECTOR: "source Postgres connector",
  PG_CONNECTOR_CAP: "Source Postgres connector",
  S3_CONNECTOR: "source S3 connector",
  S3_CONNECTOR_CAP: "Source S3 connector",

  // URLs
  WEBSITE_MARKETING: "www.tigerdata.com",
  WEBSITE_DOCS: "https://www.tigerdata.com/docs/",
  CONTACT_SALES: "sales@tigerdata.com",
  CONTACT_COMPANY: "https://www.tigerdata.com/contact/",
};

export default vars;
